VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE		= yes
QMK_SETTINGS		= yes

RGB_MATRIX_ENABLE = no
VIALRGB_ENABLE = no
ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no
COMBO_ENABLE		= no
KEY_OVERRIDE_ENABLE	= no

CONVERT_TO=liatris
