LTO_ENABLE = yes
QMK_SETTINGS = yes
# VIAL_KEYBOARD = lily58_alanjose10
VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no

COMMAND_ENABLE = no
CONSOLE_ENABLE = no

KEY_OVERRIDE_ENABLE = no

DYNAMIC_TAPPING_TERM_ENABLE = yes

VIALRGB_ENABLE = no